config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'posts/form'
  get 'posts/sum'
  
  resources :posts
  
  root 'posts#index'
  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, Post
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  resourcify
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_filter :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def show
    #@post = Post.find(params[:id])
  end
   
  def edit
    #@post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(post_params)
   
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path
  end
  
  def form
    @a 
  end
  
  def sum
    @b = 0;
    if params[:arch]
      @b = 100
    end
    
      @b = @b.to_f + params[:pl].to_f
      
      @p = Post.last
      @b = @b.to_f + @p.id.to_f
      
    
  end
 
private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test2015</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
      <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
  <% end %>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/form.html.erb
form

<h1>Форма подсчета стоимости проекта.</h1><br><br>

<%= form_tag("sum", method: :get) do %>
  Архитектурный проект <%= check_box_tag 'arch' %><br><br>
  <span class="caption">Фундамент</span><br>
  Площадь <%= number_field_tag 'pl' %> м<sup>2</sup><br><br>
  <%= submit_tag "Sum" %><br>
<% end %>
<%= link_to 'All Posts', posts_path %>

app/views/posts/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <% if can? :read, Post %>
          <td><%= link_to 'Show', post %></td>
        <% end %>
        <% if can? :update, Post %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <% if can? :destroy, Post %>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Post %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.content %>
</p>
 
<%= link_to 'Back', posts_path %>

app/views/posts/sum.html.erb
sum = <%= @b %>
<%= link_to 'Redirect to Form', posts_form_path %>